server:
  port: 8080
  servlet:
    context-path: /api

spring:
  profiles:
    active: local
  application:
    name: mini-cex

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.fffg.cex
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

logging:
  level:
    root: info
    com.fffg.cex: debug
    com.fffg.cex.mapper: debug