server:
  port: 8080
  servlet:
    context-path: /api

spring:
  profiles:
    active: local
  application:
    name: mini-cex

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.fffg.cex
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

jwt:
  secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY3ODkwYWJjZGVmZ2hpamtsbW5vcA==
  expiration: 3600000
  issuer: mini-cex

logging:
  level:
    root: info